### PR TITLE
With hyre patch 2021 11 3

### PR DESCRIPTION
**Pull request by aleksanb**
# I have made things!

### CODE REVIEW

**Comment by stianjensen** [comment]
Is this supposed to be merged, or should we force-push it on master?

**Comment by aleksanb** [comment]
> Is this supposed to be merged, or should we force-push it on master?

This was used to export a patchfile that could be applied directly into the venv on my pip-tools pr.

**Comment by stianjensen** [comment]
Is this outdated now that we're back on upstream?

**Comment by aleksanb** [comment]
> Is this outdated now that we're back on upstream?

yes

**Pull request closed without merging**
